CC      = gcc
CFLAGS  = -Wall -Werror -ansi -pedantic
CFLAGS  += -g
OBJ     = pp.o
pp: $(OBJ)
	$(CC) $(CFLAGS) -o $@ $(OBJ)
.PHONY: clean realclean
clean:
	$(RM) $(OBJ)
realclean : clean
	$(RM) fact




