#define LONGUEUR 7
#define LARGEUR 6
char petitlab[LONGUEUR][LARGEUR] =  {{FERME, OUVERT, FERME, FERME, FERME, FERME},
   {FERME, OUVERT, OUVERT, OUVERT, OUVERT, FERME},
   {FERME, OUVERT, FERME, FERME, FERME, FERME},
   {FERME, OUVERT, FERME, FERME, FERME, FERME},
   {FERME, OUVERT, FERME, FERME, FERME, FERME},
   {FERME, OUVERT, OUVERT, OUVERT, OUVERT, FERME},
   {FERME,  FERME, FERME, FERME, OUVERT, FERME}} ;
/*
XXXXX
    X
X X X
X X X
X X  
XXXXX
*/ 
